name: Auto_Update_Subs
on:
  push:
    paths:
      - 'subs/Ozime'

jobs:
  copy-content:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy Content
        run: |
          # Ähli faýllary Ozime bilen birmeňzeş etmeli
          for file in subs/*; do
            if [ "$file" != "subs/Ozime" ]; then
              cp subs/Ozime "$file"
            fi
          done

      - name: Push to GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add subs/*
          git commit -m "Robot: Subs papka täzelendi" || exit 0
          git push
          
